
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 24 07:52:51 CST 2020
//----------------------------------------------------

package gramaticaTurnosCliente_Servidor;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int cierraLlaves = 6;
  public static final int ataque = 24;
  public static final int comilla = 12;
  public static final int nombre = 11;
  public static final int cierraComilla = 14;
  public static final int turno = 2;
  public static final int coma = 7;
  public static final int espacio = 18;
  public static final int ERROR = 17;
  public static final int num = 15;
  public static final int posicionY = 26;
  public static final int posicionX = 25;
  public static final int posicion = 23;
  public static final int bool = 22;
  public static final int abreCor = 3;
  public static final int naves = 9;
  public static final int complete = 21;
  public static final int EOF = 0;
  public static final int origen = 19;
  public static final int id = 16;
  public static final int datos = 10;
  public static final int abreComilla = 13;
  public static final int error = 1;
  public static final int cierraCor = 4;
  public static final int abreLlaves = 5;
  public static final int destino = 20;
  public static final int dosPuntos = 8;
}

