/* The following code was generated by JFlex 1.7.0 */

package gramatica_guardar;
import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>src/gramatica_guardar/lexico_save.jflex</tt>
 */
public class lexico_save implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\41\1\41\1\43\1\43\1\43\22\0\1\42\3\0\1\1"+
    "\7\0\1\0\1\1\1\40\1\0\1\3\11\2\1\31\6\0\32\1"+
    "\1\5\1\1\1\6\1\1\1\4\1\1\1\12\1\35\1\14\1\25"+
    "\1\24\1\32\1\33\1\1\1\26\1\20\1\1\1\16\1\11\1\27"+
    "\1\15\1\13\1\1\1\17\1\30\1\34\1\22\1\23\1\1\1\36"+
    "\1\37\1\21\1\7\1\0\1\10\7\0\1\43\u1fa2\0\1\43\1\43"+
    "\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\1\4\1\5\1\6\1\7"+
    "\12\2\1\10\2\2\1\11\1\12\1\13\52\2\1\14"+
    "\2\2\1\15\1\16\6\2\1\17\10\2\1\20\1\21"+
    "\7\2\1\22\2\2\1\23\2\2\1\24\2\2\1\25"+
    "\13\2\1\26\2\2\1\27\4\2\1\30\1\31\4\2"+
    "\1\32\1\2\1\33\1\34\1\35\1\2\1\36\4\2"+
    "\1\37\1\2\1\40\2\2\1\41\1\42\3\2\1\43"+
    "\1\44";

  private static int [] zzUnpackAction() {
    int [] result = new int[154];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\44\0\110\0\154\0\220\0\110\0\110\0\44"+
    "\0\44\0\264\0\330\0\374\0\u0120\0\u0144\0\u0168\0\u018c"+
    "\0\u01b0\0\u01d4\0\u01f8\0\44\0\u021c\0\u0240\0\44\0\44"+
    "\0\u0264\0\u0288\0\u02ac\0\u02d0\0\u02f4\0\u0318\0\u033c\0\u0360"+
    "\0\u0384\0\u03a8\0\u03cc\0\u03f0\0\u0414\0\u0438\0\u045c\0\u0480"+
    "\0\u04a4\0\u04c8\0\u04ec\0\u0510\0\u0534\0\u0558\0\u057c\0\u05a0"+
    "\0\u05c4\0\u05e8\0\u060c\0\u0630\0\u0654\0\u0678\0\u069c\0\u06c0"+
    "\0\u06e4\0\u0708\0\u072c\0\u0750\0\u0774\0\u0798\0\u07bc\0\u07e0"+
    "\0\u0804\0\u0828\0\u084c\0\u0870\0\u0894\0\u08b8\0\110\0\110"+
    "\0\u08dc\0\u0900\0\u0924\0\u0948\0\u096c\0\u0990\0\110\0\u09b4"+
    "\0\u09d8\0\u09fc\0\u0a20\0\u0a44\0\u0a68\0\u0a8c\0\u0ab0\0\110"+
    "\0\110\0\u0ad4\0\u0af8\0\u0b1c\0\u0b40\0\u0b64\0\u0b88\0\u0bac"+
    "\0\110\0\u0bd0\0\u0bf4\0\110\0\u0c18\0\u0c3c\0\110\0\u0c60"+
    "\0\u0c84\0\110\0\u0ca8\0\u0ccc\0\u0cf0\0\u0d14\0\u0d38\0\u0d5c"+
    "\0\u0d80\0\u0da4\0\u0dc8\0\u0dec\0\u0e10\0\110\0\u0e34\0\u0e58"+
    "\0\110\0\u0e7c\0\u0ea0\0\u0ec4\0\u0ee8\0\110\0\110\0\u0f0c"+
    "\0\u0f30\0\u0f54\0\u0f78\0\u0f9c\0\u0fc0\0\110\0\110\0\110"+
    "\0\u0fe4\0\110\0\u1008\0\u102c\0\u1050\0\u1074\0\110\0\u1098"+
    "\0\110\0\u10bc\0\u10e0\0\110\0\110\0\u1104\0\u1128\0\u114c"+
    "\0\110\0\110";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[154];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\3\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\2\3\1\16\1\17"+
    "\2\3\1\20\1\21\1\22\1\3\1\23\1\3\1\24"+
    "\1\25\1\3\1\26\3\3\1\2\1\27\1\30\46\0"+
    "\6\3\2\0\20\3\1\0\6\3\6\0\2\4\42\0"+
    "\1\4\1\5\34\0\1\31\4\0\6\3\2\0\1\3"+
    "\1\32\7\3\1\33\6\3\1\0\6\3\5\0\6\3"+
    "\2\0\3\3\1\34\4\3\1\35\7\3\1\0\6\3"+
    "\5\0\6\3\2\0\4\3\1\36\1\37\1\40\11\3"+
    "\1\0\6\3\5\0\6\3\2\0\4\3\1\41\13\3"+
    "\1\0\6\3\5\0\6\3\2\0\4\3\1\42\13\3"+
    "\1\0\6\3\5\0\6\3\2\0\11\3\1\43\6\3"+
    "\1\0\6\3\5\0\6\3\2\0\13\3\1\44\4\3"+
    "\1\0\6\3\5\0\6\3\2\0\17\3\1\45\1\0"+
    "\6\3\5\0\6\3\2\0\15\3\1\46\2\3\1\0"+
    "\6\3\5\0\6\3\2\0\1\3\1\47\2\3\1\50"+
    "\6\3\1\51\4\3\1\0\6\3\5\0\6\3\2\0"+
    "\1\3\1\52\13\3\1\53\2\3\1\0\6\3\5\0"+
    "\6\3\2\0\6\3\1\54\6\3\1\55\2\3\1\0"+
    "\6\3\6\0\2\31\41\0\6\3\2\0\2\3\1\56"+
    "\15\3\1\0\6\3\5\0\6\3\2\0\13\3\1\57"+
    "\4\3\1\0\6\3\5\0\6\3\2\0\11\3\1\60"+
    "\6\3\1\0\6\3\5\0\6\3\2\0\1\3\1\61"+
    "\7\3\1\62\6\3\1\0\6\3\5\0\6\3\2\0"+
    "\17\3\1\63\1\0\6\3\5\0\6\3\2\0\1\3"+
    "\1\64\16\3\1\0\6\3\5\0\6\3\2\0\4\3"+
    "\1\65\13\3\1\0\6\3\5\0\6\3\2\0\4\3"+
    "\1\66\1\67\12\3\1\0\6\3\5\0\6\3\2\0"+
    "\7\3\1\70\10\3\1\0\6\3\5\0\6\3\2\0"+
    "\20\3\1\0\1\3\1\71\4\3\5\0\6\3\2\0"+
    "\6\3\1\72\11\3\1\0\6\3\5\0\6\3\2\0"+
    "\20\3\1\0\2\3\1\73\3\3\5\0\6\3\2\0"+
    "\1\74\17\3\1\0\6\3\5\0\6\3\2\0\12\3"+
    "\1\75\5\3\1\0\6\3\5\0\6\3\2\0\1\76"+
    "\17\3\1\0\6\3\5\0\6\3\2\0\11\3\1\77"+
    "\6\3\1\0\6\3\5\0\6\3\2\0\5\3\1\100"+
    "\12\3\1\0\6\3\5\0\6\3\2\0\5\3\1\101"+
    "\12\3\1\0\6\3\5\0\6\3\2\0\11\3\1\102"+
    "\6\3\1\0\6\3\5\0\6\3\2\0\2\3\1\103"+
    "\15\3\1\0\6\3\5\0\6\3\2\0\1\3\1\104"+
    "\16\3\1\0\6\3\5\0\6\3\2\0\6\3\1\105"+
    "\11\3\1\0\6\3\5\0\6\3\2\0\1\106\17\3"+
    "\1\0\6\3\5\0\6\3\2\0\6\3\1\107\11\3"+
    "\1\0\6\3\5\0\6\3\2\0\5\3\1\110\12\3"+
    "\1\0\6\3\5\0\6\3\2\0\15\3\1\111\2\3"+
    "\1\0\6\3\5\0\6\3\2\0\16\3\1\112\1\3"+
    "\1\0\6\3\5\0\6\3\2\0\14\3\1\113\3\3"+
    "\1\0\6\3\5\0\6\3\2\0\6\3\1\114\11\3"+
    "\1\0\6\3\5\0\6\3\2\0\4\3\1\115\4\3"+
    "\1\116\6\3\1\0\6\3\5\0\6\3\2\0\4\3"+
    "\1\117\13\3\1\0\6\3\5\0\6\3\2\0\1\3"+
    "\1\120\16\3\1\0\6\3\5\0\6\3\2\0\14\3"+
    "\1\121\3\3\1\0\6\3\5\0\6\3\2\0\1\3"+
    "\1\122\16\3\1\0\6\3\5\0\6\3\2\0\13\3"+
    "\1\123\4\3\1\0\6\3\5\0\6\3\2\0\13\3"+
    "\1\124\4\3\1\0\6\3\5\0\6\3\2\0\20\3"+
    "\1\0\3\3\1\125\2\3\5\0\6\3\2\0\20\3"+
    "\1\0\2\3\1\126\3\3\5\0\6\3\2\0\17\3"+
    "\1\102\1\0\6\3\5\0\6\3\2\0\1\3\1\127"+
    "\16\3\1\0\6\3\5\0\6\3\2\0\13\3\1\130"+
    "\4\3\1\0\6\3\5\0\6\3\2\0\4\3\1\131"+
    "\13\3\1\0\6\3\5\0\6\3\2\0\3\3\1\132"+
    "\14\3\1\0\6\3\5\0\6\3\2\0\20\3\1\0"+
    "\2\3\1\133\3\3\5\0\6\3\2\0\11\3\1\134"+
    "\6\3\1\0\6\3\5\0\6\3\2\0\3\3\1\135"+
    "\14\3\1\0\6\3\5\0\6\3\2\0\13\3\1\136"+
    "\4\3\1\0\6\3\5\0\6\3\2\0\11\3\1\137"+
    "\6\3\1\0\6\3\5\0\6\3\2\0\14\3\1\140"+
    "\3\3\1\0\6\3\5\0\6\3\2\0\6\3\1\141"+
    "\11\3\1\0\6\3\5\0\6\3\2\0\1\142\17\3"+
    "\1\0\6\3\5\0\6\3\2\0\14\3\1\143\3\3"+
    "\1\0\6\3\5\0\6\3\2\0\13\3\1\144\4\3"+
    "\1\0\6\3\5\0\6\3\2\0\14\3\1\145\3\3"+
    "\1\0\6\3\5\0\6\3\2\0\16\3\1\146\1\3"+
    "\1\0\6\3\5\0\6\3\2\0\17\3\1\147\1\0"+
    "\6\3\5\0\6\3\2\0\6\3\1\150\11\3\1\0"+
    "\6\3\5\0\6\3\2\0\6\3\1\151\11\3\1\0"+
    "\6\3\5\0\6\3\2\0\17\3\1\152\1\0\6\3"+
    "\5\0\6\3\2\0\15\3\1\153\2\3\1\0\6\3"+
    "\5\0\6\3\2\0\13\3\1\154\4\3\1\0\6\3"+
    "\5\0\6\3\2\0\5\3\1\155\12\3\1\0\6\3"+
    "\5\0\6\3\2\0\15\3\1\156\2\3\1\0\6\3"+
    "\5\0\6\3\2\0\20\3\1\0\2\3\1\157\3\3"+
    "\5\0\6\3\2\0\3\3\1\160\14\3\1\0\6\3"+
    "\5\0\3\3\1\161\2\3\2\0\20\3\1\0\6\3"+
    "\5\0\6\3\2\0\16\3\1\162\1\3\1\0\6\3"+
    "\5\0\6\3\2\0\4\3\1\163\13\3\1\0\6\3"+
    "\5\0\6\3\2\0\15\3\1\164\2\3\1\0\6\3"+
    "\5\0\6\3\2\0\17\3\1\165\1\0\6\3\5\0"+
    "\6\3\2\0\13\3\1\166\4\3\1\0\6\3\5\0"+
    "\6\3\2\0\1\3\1\167\16\3\1\0\6\3\5\0"+
    "\6\3\2\0\13\3\1\170\4\3\1\0\6\3\5\0"+
    "\6\3\2\0\17\3\1\171\1\0\6\3\5\0\6\3"+
    "\2\0\1\3\1\172\16\3\1\0\6\3\5\0\6\3"+
    "\2\0\4\3\1\173\13\3\1\0\6\3\5\0\6\3"+
    "\2\0\1\3\1\174\16\3\1\0\6\3\5\0\6\3"+
    "\2\0\3\3\1\175\14\3\1\0\6\3\5\0\6\3"+
    "\2\0\20\3\1\0\4\3\1\176\1\177\5\0\6\3"+
    "\2\0\1\3\1\200\16\3\1\0\6\3\5\0\6\3"+
    "\2\0\6\3\1\201\11\3\1\0\6\3\5\0\6\3"+
    "\2\0\17\3\1\202\1\0\6\3\5\0\6\3\2\0"+
    "\15\3\1\203\2\3\1\0\6\3\5\0\6\3\2\0"+
    "\5\3\1\204\12\3\1\0\6\3\5\0\6\3\2\0"+
    "\20\3\1\0\1\3\1\205\4\3\5\0\6\3\2\0"+
    "\6\3\1\206\11\3\1\0\6\3\5\0\6\3\2\0"+
    "\16\3\1\207\1\3\1\0\6\3\5\0\6\3\2\0"+
    "\17\3\1\210\1\0\6\3\5\0\6\3\2\0\15\3"+
    "\1\211\2\3\1\0\6\3\5\0\6\3\2\0\17\3"+
    "\1\212\1\0\6\3\5\0\6\3\2\0\13\3\1\213"+
    "\4\3\1\0\6\3\5\0\6\3\2\0\20\3\1\0"+
    "\2\3\1\214\3\3\5\0\6\3\2\0\4\3\1\215"+
    "\13\3\1\0\6\3\5\0\6\3\2\0\13\3\1\216"+
    "\4\3\1\0\6\3\5\0\6\3\2\0\4\3\1\217"+
    "\13\3\1\0\6\3\5\0\6\3\2\0\4\3\1\220"+
    "\13\3\1\0\6\3\5\0\6\3\2\0\17\3\1\221"+
    "\1\0\6\3\5\0\6\3\2\0\15\3\1\222\2\3"+
    "\1\0\6\3\5\0\6\3\2\0\16\3\1\223\1\3"+
    "\1\0\6\3\5\0\6\3\2\0\17\3\1\224\1\0"+
    "\6\3\5\0\6\3\2\0\16\3\1\225\1\3\1\0"+
    "\6\3\5\0\6\3\2\0\3\3\1\226\14\3\1\0"+
    "\6\3\5\0\6\3\2\0\13\3\1\227\4\3\1\0"+
    "\6\3\5\0\6\3\2\0\1\3\1\230\16\3\1\0"+
    "\6\3\5\0\6\3\2\0\17\3\1\231\1\0\6\3"+
    "\5\0\6\3\2\0\17\3\1\232\1\0\6\3\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4464];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\2\11\12\1\1\11\2\1\2\11"+
    "\202\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[154];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline+1, yycolumn+1, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public lexico_save(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 154) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return symbol(sym.ERROR,new String(yytext()));
            } 
            // fall through
          case 37: break;
          case 2: 
            { return symbol(sym.id,new String(yytext()));
            } 
            // fall through
          case 38: break;
          case 3: 
            { return symbol(sym.num,new String(yytext()));
            } 
            // fall through
          case 39: break;
          case 4: 
            { return symbol(sym.abreCor,new String(yytext()));
            } 
            // fall through
          case 40: break;
          case 5: 
            { return symbol(sym.cierraCor,new String(yytext()));
            } 
            // fall through
          case 41: break;
          case 6: 
            { return symbol(sym.abreParen,new String(yytext()));
            } 
            // fall through
          case 42: break;
          case 7: 
            { return symbol(sym.cierraParen,new String(yytext()));
            } 
            // fall through
          case 43: break;
          case 8: 
            { return symbol(sym.dosPuntos,new String(yytext()));
            } 
            // fall through
          case 44: break;
          case 9: 
            { return symbol(sym.enter,new String(yytext()));
            } 
            // fall through
          case 45: break;
          case 10: 
            { return symbol(sym.space,new String(yytext()));
            } 
            // fall through
          case 46: break;
          case 11: 
            { return symbol(sym.decimal,new String(yytext()));
            } 
            // fall through
          case 47: break;
          case 12: 
            { return symbol(sym.mapa,new String(yytext()));
            } 
            // fall through
          case 48: break;
          case 13: 
            { return symbol(sym.azar,new String(yytext()));
            } 
            // fall through
          case 49: break;
          case 14: 
            { return symbol(sym.azul,new String(yytext()));
            } 
            // fall through
          case 50: break;
          case 15: 
            { return symbol(sym.rojo,new String(yytext()));
            } 
            // fall through
          case 51: break;
          case 16: 
            { return symbol(sym.bool,new String(yytext()));
            } 
            // fall through
          case 52: break;
          case 17: 
            { return symbol(sym.tipo,new String(yytext()));
            } 
            // fall through
          case 53: break;
          case 18: 
            { return symbol(sym.color,new String(yytext()));
            } 
            // fall through
          case 54: break;
          case 19: 
            { return symbol(sym.verde,new String(yytext()));
            } 
            // fall through
          case 55: break;
          case 20: 
            { return symbol(sym.naves,new String(yytext()));
            } 
            // fall through
          case 56: break;
          case 21: 
            { return symbol(sym.filas,new String(yytext()));
            } 
            // fall through
          case 57: break;
          case 22: 
            { return symbol(sym.nombre,new String(yytext()));
            } 
            // fall through
          case 58: break;
          case 23: 
            { return symbol(sym.muertes,new String(yytext()));
            } 
            // fall through
          case 59: break;
          case 24: 
            { return symbol(sym.x,new String(yytext()));
            } 
            // fall through
          case 60: break;
          case 25: 
            { return symbol(sym.y,new String(yytext()));
            } 
            // fall through
          case 61: break;
          case 26: 
            { return symbol(sym.neutral,new String(yytext()));
            } 
            // fall through
          case 62: break;
          case 27: 
            { return symbol(sym.acumular,new String(yytext()));
            } 
            // fall through
          case 63: break;
          case 28: 
            { return symbol(sym.pos,new String(yytext()));
            } 
            // fall through
          case 64: break;
          case 29: 
            { return symbol(sym.planetas,new String(yytext()));
            } 
            // fall through
          case 65: break;
          case 30: 
            { return symbol(sym.columnas,new String(yytext()));
            } 
            // fall through
          case 66: break;
          case 31: 
            { return symbol(sym.mapaCiego,new String(yytext()));
            } 
            // fall through
          case 67: break;
          case 32: 
            { return symbol(sym.jugadores,new String(yytext()));
            } 
            // fall through
          case 68: break;
          case 33: 
            { return symbol(sym.neutrales,new String(yytext()));
            } 
            // fall through
          case 69: break;
          case 34: 
            { return symbol(sym.produccion,new String(yytext()));
            } 
            // fall through
          case 70: break;
          case 35: 
            { return symbol(sym.dimensiones,new String(yytext()));
            } 
            // fall through
          case 71: break;
          case 36: 
            { return symbol(sym.estadisticas,new String(yytext()));
            } 
            // fall through
          case 72: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  private String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = sym.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " char:" + yychar + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java lexico_save [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        lexico_save scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new lexico_save(reader);
          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
