
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 20 21:05:55 CST 2020
//----------------------------------------------------

package gramatica_guardar;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int cierraLlaves = 8;
  public static final int comilla = 24;
  public static final int nombre = 23;
  public static final int rojo = 13;
  public static final int cierraComilla = 26;
  public static final int coma = 11;
  public static final int jugador = 4;
  public static final int ERROR = 31;
  public static final int pos = 20;
  public static final int num = 27;
  public static final int produccion = 18;
  public static final int y = 22;
  public static final int x = 21;
  public static final int azul = 14;
  public static final int abreParen = 9;
  public static final int abreCor = 5;
  public static final int naves = 17;
  public static final int EOF = 0;
  public static final int id = 28;
  public static final int datos = 32;
  public static final int dueño = 19;
  public static final int abreComilla = 25;
  public static final int error = 1;
  public static final int cierraCor = 6;
  public static final int abreLlaves = 7;
  public static final int color = 12;
  public static final int verde = 15;
  public static final int enter = 29;
  public static final int space = 30;
  public static final int dosPuntos = 16;
  public static final int cierraParen = 10;
  public static final int planetas = 3;
  public static final int neutrales = 2;
}

