
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 17 15:35:40 CST 2020
//----------------------------------------------------

package gramatica_guardar;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int abreParen = 4;
  public static final int bool = 27;
  public static final int acumular = 13;
  public static final int dosPuntos = 8;
  public static final int planetas = 17;
  public static final int produccion = 20;
  public static final int rojo = 35;
  public static final int muertes = 21;
  public static final int verde = 36;
  public static final int dimensiones = 7;
  public static final int azul = 37;
  public static final int jugadores = 25;
  public static final int EOF = 0;
  public static final int estadisticas = 16;
  public static final int nombre = 19;
  public static final int error = 1;
  public static final int color = 34;
  public static final int pos = 22;
  public static final int ERROR = 33;
  public static final int mapaCiego = 12;
  public static final int id = 30;
  public static final int y = 24;
  public static final int x = 23;
  public static final int tipo = 26;
  public static final int filas = 9;
  public static final int azar = 11;
  public static final int neutrales = 14;
  public static final int columnas = 10;
  public static final int naves = 15;
  public static final int space = 32;
  public static final int abreCor = 2;
  public static final int enter = 31;
  public static final int cierraCor = 3;
  public static final int num = 28;
  public static final int mapa = 6;
  public static final int cierraParen = 5;
  public static final int decimal = 29;
  public static final int neutral = 18;
}

