
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 29 16:35:46 CST 2020
//----------------------------------------------------

package gramatica_juego;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int tamaño = 10;
  public static final int bool = 14;
  public static final int acum = 17;
  public static final int players = 28;
  public static final int comilla = 8;
  public static final int planetas_Neu = 27;
  public static final int dosPuntos = 4;
  public static final int human = 33;
  public static final int mostrarNaves = 19;
  public static final int abreComilla = 6;
  public static final int coma = 9;
  public static final int hard = 34;
  public static final int deaths = 26;
  public static final int columns = 11;
  public static final int name = 24;
  public static final int mostrarEstadisticas = 20;
  public static final int ships = 25;
  public static final int end = 22;
  public static final int produc = 21;
  public static final int easy = 35;
  public static final int EOF = 0;
  public static final int cierraParentesis = 3;
  public static final int error = 1;
  public static final int map = 5;
  public static final int ERROR = 41;
  public static final int mapaCiego = 16;
  public static final int id = 37;
  public static final int abreParentesis = 2;
  public static final int Neu = 18;
  public static final int name_mapa = 40;
  public static final int earths = 29;
  public static final int azar = 13;
  public static final int planetasNeu = 15;
  public static final int cierraComilla = 7;
  public static final int planets = 23;
  public static final int abreCor = 30;
  public static final int rows = 12;
  public static final int num = 38;
  public static final int cierraCor = 31;
  public static final int Comilla = 39;
  public static final int decimal = 36;
  public static final int type = 32;
}

